# Generated by Django 3.0.8 on 2020-07-31 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 1, 19, 30, 465114)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('SE', 'secondary'), ('S', 'success'), ('D', 'danger'), ('W', 'Warninginfo'), ('L', 'light'), ('D', 'dark')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
